### ISSUE TITLE
Sorry, doesn't work out of the box - cannot get it to work

### ISSUE THREAD

**Issue by kklepper** [Atriedes/openshift-boltcms-quickstart#1]
Created bolt with

rhc app create bolt php-5.4 mysql-5.5 --from-code=https://github.com/Atriedes/openshift-boltcms-quickstart

Called ''https://bolt-joe48.rhcloud.com/'' which was redirected to ''https://bolt-joe48.rhcloud.com/app''

Nothing here, **The requested URL /app was not found on this server.**

Transferred project to JBoss Central Developer Studio which created a git repo on my disk.

No interesting data there, though. Created index.php in bolt master, commited, pushed.

Worked fine:

```
[...]
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
[...]
```

But still no content. Looked via ssh. Confusing structure. 

Could not find my index.php file. Found another one in **app-root/data/latest/** which looks like default. Great.

Tried **http://bolt-joe48.rhcloud.com/app-root/data/latest**, was routed to **https://bolt-joe48.rhcloud.com/app-root/data/latest**, giving

**The requested URL /app-root/data/latest was not found on this server.**

on Firefox and **Sever Error** on Chrome.

What can I do? How can I understand what is happening?

**Comment by bludrop** [comment]
:+1: 
Has anyone gotten this to work?

**Comment by doobrie** [comment]
After you've done an install, ssh into your OpenShift instance and remove the file:

app-root/repo/php/app/config/config.yml

If you then access the root of your site, Bolt should work correctly and will ask you to create a user for loggingg on.

**Comment by semolex** [comment]
I getting such kind of error:
Error message: CLIENT_ERROR: Failed to execute action hook 'build' for
hereisid application bolt

**Comment by praswicaksono** [comment]
I will take a look shortly since this quickstart is so old

**Comment by semolex** [comment]
Thanks a lot! I appreciate that.
Cause it is the best "out-of-the-box" quickstart

**Comment by praswicaksono** [comment]
just updated to latest stable version, please confirm if it works.

**Comment by semolex** [comment]
Works really great!
Thanks!
